"use client";
import { useEffect, useState } from "react";
import { Heart, ShoppingBag, UserRound, Menu, X, ArrowUpRight, ChevronLeft, ChevronRight, Plus, Minus, Trash2, Check, Sparkles, SlidersHorizontal, Download, Pencil, Save, RotateCcw } from "lucide-react";
import { initialContent, categories, choices, type Content, type Product } from "@/data/content";
import { news, teamPortraits } from "@/data/news";
import { NewsList, NewsArticle, LatestNews } from "@/components/news";
import { Breadcrumbs, RelatedLinks } from "@/components/site-navigation";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";

type Look = { format:"STANDART"|"PRO"; selections:Record<string,string>; story:string };
type Cart = { id:string; title:string; image:string; format:string; quantity:number; price:string }[];
const nav = [["Главная","/"],["Создать куклу","/create"],["Коллекция","/collection"],["Создать одежду","/clothing"],["О нас","/about"],["Наши новости","/news"],["Вопрос-ответ","/faq"]];
const steps=["Выбери формат","Создай образ","Добавь одежду и детали","Проверь свой образ","Оформи заказ"];
function read<T>(key:string, fallback:T):T { try { const value=localStorage.getItem(key); return value?JSON.parse(value):fallback; } catch { return fallback; } }
function A({href,children,className="",...props}:React.AnchorHTMLAttributes<HTMLAnchorElement> & {href:string}) { return <a href={href} className={className} {...props}>{children}</a>; }
function ButtonLink({href,children,secondary=false}:{href:string;children:React.ReactNode;secondary?:boolean}) { return <A href={href} className={secondary?"btn btn-ghost":"btn btn-dark"}>{children}</A>; }
function ProductCard({p,favorite,toggle}:{p:Product;favorite:boolean;toggle:(id:string)=>void}) { return <article className="product-card"><div className="product-photo"><A href={`/collection/${p.id}`} aria-label={`Подробнее: ${p.title}`}><img src={p.image} alt={p.title} loading="lazy" decoding="async"/></A><button className={favorite?"heart active":"heart"} onClick={()=>toggle(p.id)} aria-label={favorite?"Убрать из избранного":"Добавить в избранное"}><Heart size={20} fill={favorite?"currentColor":"none"}/></button></div><div className="product-text"><span className="eyebrow">{p.tags[0]||"Образ"}</span><div className="split"><h3><A href={`/collection/${p.id}`}>{p.title}</A></h3><span className="price-placeholder">{p.price}</span></div><p>{p.description}</p><A className="text-link" href={`/collection/${p.id}`}>Подробнее <ArrowUpRight size={17}/></A></div></article>; }
function SectionHead({label,title,aside}:{label:string;title:string;aside?:React.ReactNode}) { return <div className="section-head"><div><span className="eyebrow">{label}</span><h2>{title}</h2></div>{aside}</div>; }
export default function Site({initialPath="/"}:{initialPath?:string}){
 const [path,setPath]=useState(initialPath); const [content,setContent]=useState<Content>(initialContent);const [favorites,setFavorites]=useState<string[]>([]);const [cart,setCart]=useState<Cart>([]);const [look,setLook]=useState<Look>({format:"STANDART",selections:{},story:""});const [menu,setMenu]=useState(false);const [filter,setFilter]=useState("Все образы");const [sort,setSort]=useState("По умолчанию");const [review,setReview]=useState(0);const [cat,setCat]=useState(categories[0]);const [checkoutStep,setCheckoutStep]=useState(0);const [order,setOrder]=useState(false);const [clothesTab,setClothesTab]=useState("Готовые образы");const [clothColor,setClothColor]=useState("Розовый");const [notice,setNotice]=useState(""); const [editJson,setEditJson]=useState("");
 useEffect(()=>{setPath(window.location.pathname);setContent(read("mod-content",initialContent));setFavorites(read("mod-favorites",[]));setCart(read("mod-cart",[]));setLook(read("mod-look",{format:"STANDART",selections:{},story:""}));setOrder(read("mod-order",false));},[]);
 useEffect(()=>{
  const scrollToAnchor=()=>{try{const id=decodeURIComponent(window.location.hash.slice(1));if(id)document.getElementById(id)?.scrollIntoView({behavior:"instant",block:"start"});}catch{}};
  const frame=requestAnimationFrame(scrollToAnchor);
  window.addEventListener("hashchange",scrollToAnchor);
  return()=>{cancelAnimationFrame(frame);window.removeEventListener("hashchange",scrollToAnchor)};
 },[path]);
 useEffect(()=>{if(notice){const t=setTimeout(()=>setNotice(""),3500);return()=>clearTimeout(t)}},[notice]);
 const updateLook=(v:Look)=>{setLook(v);localStorage.setItem("mod-look",JSON.stringify(v));};
 const saveCart=(v:Cart)=>{setCart(v);localStorage.setItem("mod-cart",JSON.stringify(v));};
 const toggle=(id:string)=>{const v=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id];setFavorites(v);localStorage.setItem("mod-favorites",JSON.stringify(v));};
 const addToCart=(item:Cart[number])=>{const i=cart.findIndex(x=>x.id===item.id);const v=[...cart];if(i>=0)v[i]={...v[i],quantity:v[i].quantity+1};else v.push(item);saveCart(v);setNotice("Добавлено в корзину");};
 const saveContent=(v:Content)=>{setContent(v);localStorage.setItem("mod-content",JSON.stringify(v));};
 useEffect(()=>{
  type WebContext={registerTool:(tool:Record<string,unknown>,options:{signal:AbortSignal})=>void|Promise<void>};
  const context=(document as Document & {modelContext?:WebContext}).modelContext;
  if(!context?.registerTool)return;
  const lifecycle=new AbortController();
  const register=(tool:Record<string,unknown>)=>{try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}};
  register({name:"configure_doll",title:"Выбрать детали куклы",description:"Сохранить формат STANDART или PRO и выбранные детали в демонстрационном конструкторе.",inputSchema:{type:"object",properties:{format:{type:"string",enum:["STANDART","PRO"]},selections:{type:"object",additionalProperties:{type:"string"}},story:{type:"string"}},required:["format","selections"],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{const x=input as {format?:string;selections?:Record<string,string>;story?:string};if(!x||!["STANDART","PRO"].includes(x.format||"")||!x.selections||typeof x.selections!=="object"||Object.entries(x.selections).some(([k,v])=>!categories.includes(k)||typeof v!=="string"))throw Error("Некорректные параметры образа");const v={format:x.format as "STANDART"|"PRO",selections:x.selections,story:x.story||""};updateLook(v);return {saved:true,format:v.format,selected:Object.keys(v.selections).length};}});
  register({name:"add_current_doll_to_cart",title:"Добавить образ в корзину",description:"Добавить текущую демонстрационную куклу в локальную корзину.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute:()=>{const v=[...cart,{id:"custom-"+Date.now(),title:"Моя кукла MODYOU",image:look.selections["Внешность"]==="Образ 02"?"/images/doll-20.png":"/images/doll-18.png",format:look.format,quantity:1,price:"[Цена]"}];saveCart(v);return {added:true,cartItems:v.length,price:"Не утверждена"};}});
  return()=>lifecycle.abort();
 },[look,cart]);
 useEffect(()=>{
  const titles:Record<string,string>={"/":"Твоя кукла. Твоя история. Твой стиль.","/create":"Создать куклу — STANDART и PRO","/collection":"Коллекция кукол","/clothing":"Создать одежду","/about":"О бренде","/faq":"Вопрос — ответ","/favorites":"Избранное","/cart":"Корзина","/checkout":"Оформление заказа","/tracking":"Отслеживание заказа","/account":"Личный кабинет","/app":"Мобильное приложение","/editor":"Редактор контента","/my-look":"Мой образ","/constructor/standart":"Конструктор STANDART","/constructor/pro":"Конструктор PRO","/info/privacy":"Политика конфиденциальности","/info/terms":"Пользовательское соглашение","/info/delivery":"Условия доставки","/info/payment":"Оплата"};
  const product=content.products.find(p=>path===`/collection/${p.id}`);
  const title=product?.title||news.find(n=>path===`/news/${n.slug}`)?.title||(path==="/news"?"Наши новости":undefined)||titles[path]||"Страница не найдена";
  document.title=`${title} | MODYOU`;
  document.querySelector('meta[name="description"]')?.setAttribute("content",product?.description||`${title}. MODYOU — персонализированные куклы, одежда и цифровой конструктор образа.`);
 },[path,content]);
 useEffect(()=>{if(!menu)return;const close=(event:KeyboardEvent)=>{if(event.key==="Escape")setMenu(false)};window.addEventListener("keydown",close);return()=>window.removeEventListener("keydown",close)},[menu]);
 const knownPath=["/","/create","/collection","/clothing","/about","/faq","/favorites","/cart","/checkout","/tracking","/account","/app","/editor","/my-look","/constructor/standart","/constructor/pro","/info/privacy","/info/terms","/info/delivery","/info/payment","/news"].includes(path)||news.some(n=>path===`/news/${n.slug}`)||content.products.some(p=>path===`/collection/${p.id}`);
 const go=(href:string)=>{window.location.href=href};
 const products=[...content.products].filter(p=>filter==="Все образы"||p.tags.includes(filter));if(sort==="По названию")products.sort((a,b)=>a.title.localeCompare(b.title,"ru"));
 const item=content.products.find(x=>path==`/collection/${x.id}`);
 const newsItem=news.find(n=>path===`/news/${n.slug}`);
 const format=path.includes("/pro")?"PRO":"STANDART";
 const dollImg=look.selections["Внешность"]==="Образ 02"?"/images/doll-20.png":"/images/doll-18.png";
 const titleByPath=path.startsWith("/constructor")?"Конструктор":path.startsWith("/collection")?"Коллекция":path.startsWith("/checkout")?"Оформление заказа":"MODYOU";
 const formatCard=(kind:"standart"|"pro")=>{const f=content[kind];return <article className={`format-card ${kind}`}><div className="format-top"><span className="eyebrow">ПЕРСОНАЛИЗАЦИЯ</span><span className="format-number">0{kind==="standart"?1:2} / 02</span></div><h3>{f.name}</h3><p className="format-sub">{f.subtitle}</p><p>{f.description}</p><div className="format-meta"><span>{f.includes}</span><span>{f.time}</span><strong>{f.price}</strong></div><ButtonLink href={`/constructor/${kind}`}>Создать {f.name}</ButtonLink></article>};
 const preview=<div className="preview-image"><img src={dollImg} alt="Предпросмотр образа куклы"/><span className="preview-tag">DEMO PREVIEW</span></div>;
 return <><a className="skip-link" href="#main-content">Перейти к содержимому</a><header className="header"><div className="header-inner"><A href="/" className="logo">MOD<span>YOU</span><i>✳</i></A><nav className="desktop-nav" aria-label="Основное меню">{nav.map(([n,h])=><A key={h} href={h} className={path===h||(h!=="/"&&path.startsWith(h+"/"))?"current":""} aria-current={path===h?"page":undefined}>{n}</A>)}</nav><div className="header-actions"><A href="/account" aria-label="Личный кабинет"><UserRound size={20}/></A><A href="/favorites" aria-label={`Избранное: ${favorites.length}`}><Heart size={20}/>{favorites.length>0&&<sup>{favorites.length}</sup>}</A><A href="/cart" aria-label={`Корзина: ${cart.length}`}><ShoppingBag size={20}/>{cart.length>0&&<sup>{cart.reduce((n,x)=>n+x.quantity,0)}</sup>}</A><A href="/app" className="download">Скачать приложение</A></div><button className="mobile-menu-button" onClick={()=>setMenu(!menu)} aria-expanded={menu} aria-controls="mobile-navigation" aria-label={menu?"Закрыть меню":"Открыть меню"}>{menu?<X/>:<Menu/>}</button></div>{menu&&<nav id="mobile-navigation" className="mobile-nav" aria-label="Мобильное меню">{nav.map(([n,h])=><A key={h} href={h}>{n}</A>)}<A href="/account">Личный кабинет</A><A href="/favorites">Избранное</A><A href="/cart">Корзина</A><A href="/app">Скачать приложение</A></nav>}</header>
 <main id="main-content">
 <Breadcrumbs path={path} productTitle={item?.title}/>
 {path==="/news"&&<NewsList/>}
 {newsItem&&<NewsArticle item={newsItem}/>}
 {path==="/"&&<><section className="hero"><div className="hero-copy"><span className="eyebrow">ПЕРСОНАЛЬНО. ПО-ТВОЕМУ.</span><h1>{content.heroTitle}</h1><p>{content.heroText}</p><div className="hero-buttons"><ButtonLink href="/create">Создать свою куклу</ButtonLink><ButtonLink href="/collection" secondary>Посмотреть коллекцию</ButtonLink></div><div className="hero-bottom"><span>01 / 05</span><span>Кукла, в которой узнаёшь себя</span></div></div><div className="hero-visual"><div className="hero-blob"><img src="/images/doll-18.png" alt="Пример персонализированной куклы MODYOU"/></div><span className="orbit-label">ONE OF A KIND ✳</span><span className="hero-stamp">made<br/>for you</span></div></section>
 <section className="section wrap" id="how"><SectionHead label="ПРОЦЕСС" title="От идеи до твоей истории"/><div className="steps">{steps.map((s,i)=><A href={["/create","/constructor/standart","/clothing","/my-look","/cart"][i]} className="step" key={s}><span>0{i+1}</span><h3>{s}</h3><p>{["STANDART или PRO","Начни с внешности и характера","Дополни образ своим стилем","Посмотри, что получилось","Демонстрационный путь заказа"][i]}</p></A>)}</div></section>
 <section className="section soft"><div className="wrap"><SectionHead label="ВЫБЕРИ СВОЙ ПУТЬ" title="Два способа быть собой"/><div className="format-grid">{formatCard("standart")}{formatCard("pro")}</div></div></section>
 <section className="section wrap"><SectionHead label="ВДОХНОВЕНИЕ" title="У каждого образа — своя история" aside={<A href="/collection" className="text-link">Вся коллекция <ArrowUpRight size={18}/></A>}/><div className="product-grid">{content.products.slice(0,3).map(p=><ProductCard key={p.id} p={p} favorite={favorites.includes(p.id)} toggle={toggle}/>)}</div></section>
 <section className="section wrap why"><div><span className="eyebrow">ПОЧЕМУ MODYOU</span><h2>Больше, чем просто кукла</h2><p>Каждый образ становится маленьким отражением человека, его вкуса и личной истории.</p><ButtonLink href="/about" secondary>О бренде</ButtonLink></div><div className="why-grid">{[["01","Персональность","Уникальный образ, созданный тобой."],["02","Цифровой конструктор","Твоя идея обретает форму шаг за шагом."],["03","Детали","Одежда и аксессуары продолжают историю."],["04","Выбор","Два уровня персонализации — STANDART и PRO."]].map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section>
 <section className="section testimonial"><div className="wrap quote-wrap"><div><span className="eyebrow">ОТЗЫВЫ</span><h2>Истории, которыми хочется делиться</h2></div><div className="quote-card"><span className="quote-mark">“</span><blockquote>{content.reviews[review]?.quote}</blockquote><div className="split"><p>{content.reviews[review]?.name} · {content.reviews[review]?.city}</p><div className="slider-buttons"><button onClick={()=>setReview((review-1+content.reviews.length)%content.reviews.length)} aria-label="Предыдущий отзыв"><ChevronLeft/></button><button onClick={()=>setReview((review+1)%content.reviews.length)} aria-label="Следующий отзыв"><ChevronRight/></button></div></div></div></div></section>
 <section className="app-banner wrap"><div><span className="eyebrow">MODYOU В ТВОЁМ ТЕЛЕФОНЕ</span><h2>Создавай свою куклу ещё удобнее</h2><p>Приложение готовится. Ссылки для скачивания появятся здесь после запуска.</p><ButtonLink href="/app" secondary>Подробнее</ButtonLink></div><div className="phone-art"><div className="phone-screen"><span>MODYOU</span><img src="/images/doll-20.png" alt="Пример экрана приложения"/><small>ТВОЙ ОБРАЗ</small></div></div></section>
 <LatestNews/>
 <section className="final-cta"><div className="wrap"><span className="eyebrow">НАЧНИ СВОЮ ИСТОРИЮ</span><h2>Создай куклу, которая расскажет твою историю.</h2><ButtonLink href="/create">Начать создание</ButtonLink></div></section></>}
 {path==="/create"&&<section className="page wrap"><div className="page-intro centered"><span className="eyebrow">СОЗДАТЬ КУКЛУ</span><h1>Какую куклу ты хочешь создать?</h1><p>Выбери уровень персонализации. Образ можно изменить в конструкторе.</p></div><div className="format-grid choose">{formatCard("standart")}{formatCard("pro")}</div></section>}
 {["/constructor/standart","/constructor/pro"].includes(path)&&<section className="constructor-page"><div className="wrap"><div className="constructor-heading"><div><span className="eyebrow">MODYOU STUDIO / {format}</span><h1>Создай свой образ</h1><p>Выбирай детали и смотри, как складывается твоя история.</p></div><A href="/create" className="text-link">Изменить формат</A></div><div className="studio"><aside className="studio-nav"><span className="eyebrow">КАТЕГОРИИ</span>{categories.map((c,i)=><button key={c} className={cat===c?"active":""} onClick={()=>setCat(c)}><span>{String(i+1).padStart(2,"0")}</span>{c}</button>)}</aside><div className="studio-preview">{preview}<div className="preview-caption"><span>Твой образ · {format}</span><span>Предпросмотр</span></div></div><aside className="studio-controls"><span className="eyebrow">ШАГ {String(categories.indexOf(cat)+1).padStart(2,"0")} / 09</span><h2>{cat}</h2>{cat==="История персонажа"?<><p>Расскажи о персонаже своими словами.</p><textarea aria-label="История персонажа" placeholder="Моя история начинается..." value={look.story} onChange={e=>updateLook({...look,format,story:e.target.value})}/></>:<><p>Выбери один из демонстрационных вариантов. Изображения и точные параметры можно добавить позже.</p><div className="option-list">{(choices[cat]||[]).map((o,i)=><button className={look.selections[cat]===o?"option selected":"option"} key={o} onClick={()=>updateLook({...look,format,selections:{...look.selections,[cat]:o}})}><span className={`swatch swatch-${i}`}/><span>{o}</span>{look.selections[cat]===o&&<Check size={18}/>}</button>)}</div></>}<div className="studio-summary"><span>Ваш образ</span><strong>{Object.keys(look.selections).length} деталей выбрано</strong><small>Итоговая цена: {content[format.toLowerCase() as "standart"|"pro"].price}</small></div><div className="studio-actions"><button className="btn btn-ghost" onClick={()=>{updateLook({...look,format});setNotice("Образ сохранён на этом устройстве")}}>Сохранить образ</button><button className="btn btn-dark" onClick={()=>{updateLook({...look,format});go("/my-look")}}>Предпросмотр</button></div><button className="text-link under-action" onClick={()=>{updateLook({...look,format});go("/my-look")}}>Продолжить к моему образу <ArrowUpRight size={16}/></button></aside></div></div></section>}
 {path==="/my-look"&&<section className="page wrap"><div className="page-intro"><span className="eyebrow">ТВОЯ ИСТОРИЯ</span><h1>Мой образ</h1><p>Проверь детали перед добавлением в корзину.</p></div><div className="look-layout"><div className="look-photo">{preview}</div><div className="look-details"><span className="eyebrow">ПЕРСОНАЛИЗИРОВАННАЯ КУКЛА</span><h2>MODYOU {look.format}</h2><p>{content[look.format.toLowerCase() as "standart"|"pro"].subtitle}</p><dl>{categories.slice(0,-1).map(c=><div key={c}><dt>{c}</dt><dd>{look.selections[c]||"[Не выбрано]"}</dd></div>)}<div><dt>История персонажа</dt><dd>{look.story||"[История не добавлена]"}</dd></div><div><dt>Итоговая цена</dt><dd>{content[look.format.toLowerCase() as "standart"|"pro"].price}</dd></div></dl><div className="button-row"><ButtonLink href={`/constructor/${look.format.toLowerCase()}`} secondary>Изменить образ</ButtonLink><button className="btn btn-ghost" onClick={()=>setNotice("Образ сохранён на этом устройстве")}>Сохранить</button><button className="btn btn-dark" onClick={()=>{addToCart({id:"custom-"+Date.now(),title:"Моя кукла MODYOU",image:dollImg,format:look.format,quantity:1,price:"[Цена]"});go("/cart")}}>Добавить в корзину</button></div></div></div></section>}
 {path==="/collection"&&<section className="page wrap"><div className="page-intro"><span className="eyebrow">КОЛЛЕКЦИЯ MODYOU</span><h1>Найди своё вдохновение</h1><p>Примеры образов для знакомства с миром MODYOU. Фотографии и цены пока демонстрационные.</p></div><div className="catalog-tools"><div className="filter-row">{["Все образы","Новинки","Популярные","Идеи для подарка"].map(f=><button key={f} className={filter===f?"pill active":"pill"} onClick={()=>setFilter(f)}>{f}</button>)}</div><label className="sort">Сортировка <select value={sort} onChange={e=>setSort(e.target.value)}><option>По умолчанию</option><option>По названию</option></select></label></div><div className="product-grid four">{products.map(p=><ProductCard key={p.id} p={p} favorite={favorites.includes(p.id)} toggle={toggle}/>)}</div></section>}
 {item&&<section className="page wrap"><div className="look-layout"><div className="look-photo"><div className="preview-image"><img src={item.image} alt={item.title}/></div></div><div className="look-details"><span className="eyebrow">КОЛЛЕКЦИЯ / ДЕМОНСТРАЦИОННЫЙ ОБРАЗ</span><h1>{item.title}</h1><p>{item.description}</p><p className="big-price">{item.price}</p><div className="button-row"><button className="btn btn-dark" onClick={()=>addToCart({id:item.id,title:item.title,image:item.image,format:"Коллекция",quantity:1,price:item.price})}>Добавить в корзину</button><button className="btn btn-ghost" onClick={()=>toggle(item.id)}>{favorites.includes(item.id)?"В избранном":"В избранное"}</button></div><p className="fine">Комплектация и стоимость будут уточнены перед запуском продаж.</p><A href="/collection" className="text-link">Вернуться в коллекцию</A></div></div></section>}
 {path==="/clothing"&&<section className="page wrap"><div className="page-intro"><span className="eyebrow">ТВОЙ СТИЛЬ ПРОДОЛЖАЕТСЯ</span><h1>Создай одежду</h1><p>Готовые идеи для образа или пространство для собственного дизайна.</p></div><div className="filter-row spacious">{["Готовые образы","Свои дизайны"].map(t=><button key={t} className={clothesTab===t?"pill active":"pill"} onClick={()=>setClothesTab(t)}>{t}</button>)}</div>{clothesTab==="Готовые образы"?<div className="clothing-grid">{["Повседневный образ","Нежный образ","Образ для подарка"].map((n,i)=><article className="clothing-card" key={n}><div className={`clothing-art clothing-${i}`}><img src={`/images/doll-${i===1?20:18}.png`} alt={`Пример: ${n}`}/></div><h3>{n}</h3><p>[Описание и цена будут добавлены]</p><button className="text-link" onClick={()=>addToCart({id:"clothing-"+i,title:n,image:`/images/doll-${i===1?20:18}.png`,format:"Одежда",quantity:1,price:"[Цена]"})}>Добавить в корзину <ArrowUpRight size={16}/></button></article>)}</div>:<div className="clothing-builder"><div className="clothing-art large"><img src="/images/doll-20.png" alt="Демонстрационный образ для дизайна одежды"/></div><div><span className="eyebrow">ДЕМО-КОНСТРУКТОР</span><h2>Твой дизайн начинается здесь</h2><p>Выбери настроение и опиши идею. Загрузка эскиза и точная визуализация появятся после разработки каталога одежды.</p><label>Цветовая идея<select value={clothColor} onChange={e=>setClothColor(e.target.value)}><option>Розовый</option><option>Сиреневый</option><option>Голубой</option></select></label><label>Описание дизайна<textarea placeholder="Расскажи о своём дизайне"/></label><button className="btn btn-dark" onClick={()=>setNotice(`Эскиз «${clothColor}» сохранён как идея на этом экране`)}>Сохранить идею</button></div></div>}</section>}
 {path==="/about"&&<section className="page wrap"><div className="page-intro"><span className="eyebrow">О БРЕНДЕ</span><h1>Вещи становятся ближе, когда в них есть ты.</h1><p>MODYOU — идея персонализированной куклы, которая отражает внешность, стиль, интересы и историю человека.</p></div><div className="about-block lilac" id="mission"><span className="eyebrow">НАША МИССИЯ</span><h2>Помочь человеку увидеть свою индивидуальность в новом образе.</h2><p>Образ создаётся самостоятельно через цифровой конструктор. Кукла задумана как персональный объект, связанный с человеком и его историей.</p></div><SectionHead label="ЛЮДИ ЗА ИДЕЕЙ" title="Наша команда"/><div className="team-grid" id="team">{content.team.map((n,i)=><article key={n}><a className={`team-portrait team-${i}`} href={teamPortraits[n]||"/news/komanda-modyou"} target={teamPortraits[n]?"_blank":undefined} rel="noreferrer" aria-label={`Рассмотреть кукольный образ: ${n}`}>{teamPortraits[n]?<img src={teamPortraits[n]} alt={`Кукольный образ: ${n}`} width="1024" height="1536" loading="lazy" decoding="async"/>:<span>Кукольный образ</span>}<span className="portrait-caption">Рассмотреть образ <ArrowUpRight size={15}/></span></a><h3>{n}</h3><a href="/news/komanda-modyou" className="text-link">Команда MODYOU <ArrowUpRight size={15}/></a></article>)}</div><div className="about-bottom"><article id="history"><span className="eyebrow">ИСТОРИЯ</span><h2>Начало MODYOU</h2><p>Проект родился из идеи создать индивидуальную куклу по образу человека и дать каждому возможность самостоятельно собрать её характер и стиль.</p></article><article id="partners"><span className="eyebrow">ПАРТНЁРЫ</span><h2>Создаём вместе</h2><p>Потенциальные партнёры проекта:</p><p><a className="text-link" href="https://meritogroup.ru/" target="_blank" rel="noopener noreferrer">Merito Group <ArrowUpRight size={15} aria-hidden="true"/></a><br/>производство и 3D-печать</p><p><a className="text-link" href="https://market.yandex.ru/" target="_blank" rel="noopener noreferrer">Яндекс Маркет <ArrowUpRight size={15} aria-hidden="true"/></a><br/>онлайн-продажи</p><p><a className="text-link" href="https://befree.ru/" target="_blank" rel="noopener noreferrer">befree <ArrowUpRight size={15} aria-hidden="true"/></a><br/>fashion-коллаборации</p><p><a className="text-link" href="https://all4events.ru/" target="_blank" rel="noopener noreferrer">All4Events <ArrowUpRight size={15} aria-hidden="true"/></a><br/>мероприятия и event-направление</p><p><a className="text-link" href="https://nktech3d.ru/" target="_blank" rel="noopener noreferrer">NKTech3D <ArrowUpRight size={15} aria-hidden="true"/></a><br/>3D-печать и прототипирование</p></article><article id="contacts"><span className="eyebrow">КОНТАКТЫ</span><h2>Будем на связи</h2><p>{content.contact}</p></article></div></section>}
 {path==="/faq"&&<section className="page wrap narrow"><div className="page-intro"><span className="eyebrow">ПОМОЩЬ</span><h1>Вопрос — ответ</h1><p>Собрали главное о создании и заказе. Ответы будут дополнены по мере утверждения условий проекта.</p></div><Accordion className="faq-list" type="single" collapsible>{content.faq.map((f,i)=><AccordionItem key={i} value={`item-${i}`}><AccordionTrigger>{f.q}</AccordionTrigger><AccordionContent>{f.a}</AccordionContent></AccordionItem>)}</Accordion><div className="faq-cta"><h2>Готов создать свой образ?</h2><ButtonLink href="/create">Создать куклу</ButtonLink></div></section>}
 {path==="/favorites"&&<section className="page wrap"><div className="page-intro"><span className="eyebrow">СОХРАНЁННОЕ</span><h1>Избранное</h1></div>{favorites.length?<div className="product-grid four">{content.products.filter(p=>favorites.includes(p.id)).map(p=><ProductCard key={p.id} p={p} favorite toggle={toggle}/>)}</div>:<div className="empty"><Heart size={34}/><h2>Пока ничего не сохранено</h2><p>Отмечай понравившиеся образы сердцем.</p><ButtonLink href="/collection">Посмотреть коллекцию</ButtonLink></div>}</section>}
 {path==="/cart"&&<section className="page wrap"><div className="page-intro"><span className="eyebrow">ТВОЙ ВЫБОР</span><h1>Корзина</h1><p>Демонстрационный заказ: цены будут известны после утверждения предложения.</p></div>{cart.length?<div className="cart-layout"><div className="cart-items">{cart.map(x=><article className="cart-item" key={x.id}><img src={x.image} alt={x.title}/><div><span className="eyebrow">{x.format}</span><h3>{x.title}</h3><p>{x.price}</p><div className="quantity"><button onClick={()=>saveCart(cart.map(y=>y.id===x.id?{...y,quantity:Math.max(1,y.quantity-1)}:y))} aria-label="Уменьшить количество"><Minus size={15}/></button><span>{x.quantity}</span><button onClick={()=>saveCart(cart.map(y=>y.id===x.id?{...y,quantity:y.quantity+1}:y))} aria-label="Увеличить количество"><Plus size={15}/></button></div></div><div className="cart-actions"><button onClick={()=>saveCart(cart.filter(y=>y.id!==x.id))} aria-label="Удалить"><Trash2 size={18}/></button><A href={x.id.startsWith("custom")?"/my-look":`/collection/${x.id}`} className="text-link">Изменить</A></div></article>)}</div><aside className="cart-summary"><span className="eyebrow">ИТОГ ЗАКАЗА</span><h2>Твой заказ</h2><div className="split"><span>Товаров</span><span>{cart.reduce((n,x)=>n+x.quantity,0)}</span></div><div className="split total"><span>Итого</span><strong>[Итоговая сумма]</strong></div><p>Стоимость и условия оплаты уточняются.</p><ButtonLink href="/checkout">Перейти к оформлению</ButtonLink></aside></div>:<div className="empty"><ShoppingBag size={36}/><h2>Твоя корзина пока пуста</h2><p>Начни с создания своей куклы или загляни в коллекцию.</p><ButtonLink href="/create">Создать куклу</ButtonLink></div>}</section>}
 {path==="/checkout"&&<section className="page wrap narrow"><div className="page-intro"><span className="eyebrow">ДЕМОНСТРАЦИОННЫЙ СЦЕНАРИЙ</span><h1>Оформление заказа</h1><p>Форма показывает путь заказа. Данные не отправляются и оплата не производится.</p></div>{cart.length?<><div className="checkout-progress">{["Покупатель","Доставка","Проверка","Оплата"].map((s,i)=><span className={i<=checkoutStep?"active":""} key={s}>{i+1}. {s}</span>)}</div><form className="checkout-form" onSubmit={e=>{e.preventDefault();if(checkoutStep<3)setCheckoutStep(checkoutStep+1);else{setOrder(true);localStorage.setItem("mod-order","true");go("/tracking")}}}>{checkoutStep===0&&<><h2>Данные покупателя</h2><label>Имя<input placeholder="Ваше имя" required/></label><label>Телефон<input type="tel" placeholder="Телефон" required/></label><label>Электронная почта<input type="email" placeholder="Email" required/></label></>}{checkoutStep===1&&<><h2>Доставка</h2><p>Способы и условия доставки будут опубликованы после утверждения.</p><label>Город<input placeholder="Ваш город" required/></label><label>Комментарий<textarea placeholder="Пожелания к доставке"/></label></>}{checkoutStep===2&&<><h2>Проверь заказ</h2>{cart.map(x=><div className="split review-line" key={x.id}><span>{x.title} · {x.quantity} шт.</span><span>{x.price}</span></div>)}<p>Окончательная стоимость и условия заказа будут подтверждены отдельно.</p></>}{checkoutStep===3&&<><h2>Оплата</h2><div className="demo-payment"><Sparkles size={30}/><h3>Демонстрационная оплата</h3><p>Платёжная система пока не подключена. Нажатие кнопки создаст только локальный пример заказа на этом устройстве.</p></div></>}<div className="button-row">{checkoutStep>0&&<button type="button" className="btn btn-ghost" onClick={()=>setCheckoutStep(checkoutStep-1)}>Назад</button>}<button className="btn btn-dark" type="submit">{checkoutStep===3?"Завершить демо-заказ":"Продолжить"}</button></div></form></>:<div className="empty"><h2>Сначала добавь образ в корзину</h2><ButtonLink href="/create">Создать куклу</ButtonLink></div>}</section>}
 {path==="/tracking"&&<section className="page wrap narrow"><div className="page-intro"><span className="eyebrow">СТАТУС ЗАКАЗА / ДЕМО</span><h1>Отслеживание заказа</h1><p>{order?"Пример заказа сохранён только на этом устройстве.":"После демонстрационного оформления здесь появится пример заказа."}</p></div><div className="timeline">{["Заказ оформлен","Подтверждение","Создание куклы","Готово","Передано в доставку","Получено"].map((s,i)=><div className={order&&i===0?"done":""} key={s}><span>{order&&i===0?<Check size={18}/>:String(i+1).padStart(2,"0")}</span><div><h3>{s}</h3><p>{i===0&&order?"Демонстрационный шаг завершён":"Ожидает подтверждения в реальном сервисе"}</p></div></div>)}</div><ButtonLink href="/account" secondary>В личный кабинет</ButtonLink></section>}
 {path==="/account"&&<section className="page wrap"><div className="page-intro"><span className="eyebrow">ЛИЧНОЕ ПРОСТРАНСТВО / ДЕМО</span><h1>Личный кабинет</h1><p>Образы и избранное сохраняются в браузере этого устройства. Регистрация появится после подключения сервиса.</p></div><div className="account-grid"><A href="/tracking"><span>01</span><h2>Мои заказы</h2><p>{order?"1 демонстрационный заказ":"Заказов пока нет"}</p></A><A href="/my-look"><span>02</span><h2>Мои образы</h2><p>Последний сохранённый образ</p></A><A href="/favorites"><span>03</span><h2>Избранное</h2><p>{favorites.length} сохранённых образов</p></A><article><span>04</span><h2>Личные данные</h2><p>[Профиль после подключения аккаунта]</p></article><article><span>05</span><h2>Настройки</h2><p>[Настройки после подключения аккаунта]</p></article></div></section>}
 {path==="/app"&&<section className="page wrap app-page"><div><span className="eyebrow">MODYOU APP</span><h1>Создавай свою куклу ещё удобнее.</h1><p>Место для мобильного приложения уже подготовлено. Ссылки на магазины и QR-код будут добавлены после запуска.</p><div className="store-links"><span>App Store · [ссылка готовится]</span><span>Google Play · [ссылка готовится]</span></div><div className="qr-placeholder">Место для QR-кода</div><ButtonLink href="/constructor/standart">Попробовать конструктор на сайте</ButtonLink></div><div className="app-art"><div className="phone-screen"><span>MODYOU</span><img src="/images/doll-18.png" alt="Пример интерфейса конструктора"/><small>ТВОЯ ИСТОРИЯ</small></div></div></section>}
 {path==="/editor"&&<section className="page wrap narrow"><div className="page-intro"><span className="eyebrow">РЕДАКТОР КОНТЕНТА</span><h1>Настрой свой MODYOU</h1><p>Изменения сохраняются в браузере этого устройства. Для переноса на опубликованный сайт экспортируй JSON и передай его разработчику. Эта страница не защищена паролем.</p></div><div className="editor"><h2>Основные тексты</h2><label>Заголовок главной<input value={content.heroTitle} onChange={e=>saveContent({...content,heroTitle:e.target.value})}/></label><label>Описание главной<textarea value={content.heroText} onChange={e=>saveContent({...content,heroText:e.target.value})}/></label><label>Контакты<input value={content.contact} onChange={e=>saveContent({...content,contact:e.target.value})}/></label><h2>Данные сайта</h2><p>В редакторе JSON можно заменить цены, карточки коллекции, изображения, команду, отзывы и FAQ. Укажи адрес изображения или путь к файлу в каталоге public.</p><textarea className="json-editor" aria-label="JSON данных сайта" value={editJson||JSON.stringify(content,null,2)} onChange={e=>setEditJson(e.target.value)}/><div className="button-row"><button className="btn btn-dark" onClick={()=>{try{saveContent(JSON.parse(editJson||JSON.stringify(content)));setEditJson("");setNotice("Контент сохранён локально")}catch{setNotice("Проверь синтаксис JSON")}}}><Save size={17}/> Сохранить JSON</button><button className="btn btn-ghost" onClick={()=>{const blob=new Blob([JSON.stringify(content,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="modyou-content.json";a.click();URL.revokeObjectURL(url)}}><Download size={17}/> Экспорт</button><button className="btn btn-ghost" onClick={()=>{localStorage.removeItem("mod-content");setContent(initialContent);setEditJson("");setNotice("Исходный контент восстановлен")}}><RotateCcw size={17}/> Сбросить</button></div></div></section>}
 {["/info/privacy","/info/terms","/info/delivery","/info/payment"].includes(path)&&<section className="page wrap narrow"><div className="page-intro"><span className="eyebrow">ИНФОРМАЦИЯ</span><h1>{({privacy:"Политика конфиденциальности",terms:"Пользовательское соглашение",delivery:"Условия доставки",payment:"Оплата"} as Record<string,string>)[path.split("/")[2]]||"Информация"}</h1><p>Документ и условия будут опубликованы после юридического утверждения. Сейчас сайт работает как демонстрационный прототип.</p></div><ButtonLink href="/" secondary>На главную</ButtonLink></section>}
 {!knownPath&&<section className="page wrap narrow"><div className="page-intro"><span className="eyebrow">ОШИБКА 404</span><h1>Страница не найдена</h1><p>Проверь адрес или вернись на главную.</p></div><ButtonLink href="/">На главную</ButtonLink></section>}{knownPath&&<RelatedLinks path={path}/>}</main><footer className="footer"><div className="wrap footer-grid"><div><A href="/" className="logo">MOD<span>YOU</span><i>✳</i></A><p>Твоя кукла. Твоя история. Твой стиль.</p></div><div><h3>Навигация</h3>{nav.map(([n,h])=><A key={h} href={h}>{n}</A>)}</div><div><h3>Сервис</h3>{[["Личный кабинет","/account"],["Избранное","/favorites"],["Корзина","/cart"],["Отслеживание","/tracking"],["Редактор контента","/editor"]].map(([n,h])=><A key={h} href={h}>{n}</A>)}</div><div><h3>Информация</h3>{[["Политика конфиденциальности","/info/privacy"],["Пользовательское соглашение","/info/terms"],["Условия доставки","/info/delivery"],["Оплата","/info/payment"]].map(([n,h])=><A key={h} href={h}>{n}</A>)}<p>{content.contact}</p><small>[Социальные сети будут добавлены]</small></div></div><div className="wrap footer-bottom"><span>© MODYOU · Демонстрационный прототип</span><span>{titleByPath}</span></div></footer>{notice&&<div role="status" className="toast">{notice}</div>}{["/","/collection","/about","/faq","/app","/clothing"].includes(path)&&<A href="/create" className="mobile-create">Создать куклу</A>}</>;
}
